# Generated by Django 5.2.6 on 2025-09-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_visible',
        ),
    ]
