# Generated by Django 5.2.6 on 2025-09-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_options_payment_client_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymob_order_id',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
