# Generated by Django 5.2.6 on 2025-09-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_paymob_order_id_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymob_order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
