# Generated by Django 5.2.6 on 2025-09-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_payment_paymob_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='provider_payment_status',
        ),
    ]
