"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import environ

env = environ.Env()
environ.Env.read_env(env_file=BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
	'rest_framework_simplejwt',
    "django_cleanup.apps.CleanupConfig",
    'auth_app',
    "social_django",
    "product",
    "reviews",
    "cart",
    "order",
    "address",
    'django_celery_beat',
    'django_celery_results',
    "payment",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # لازم يكون المجلد اللي فيه base_site.html
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': env("DB_NAME"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),
        'HOST': env("DB_HOST"),
        'PORT': env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "auth_app.User" 

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "auth_app.authentication.CookieJWTAuthentication",
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,  # عدد المنتجات لكل صفحة
}


from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),   # مدة صلاحية الـ access token
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),      # مدة صلاحية الـ refresh token
    "ROTATE_REFRESH_TOKENS": False,                   # لو True، هيصدر refresh جديد مع كل refresh
    "BLACKLIST_AFTER_ROTATION": True,                 # لو بتستخدم blacklisting
    "ALGORITHM": "HS256",                             # خوارزمية التوقيع
    "SIGNING_KEY": SECRET_KEY,                        # المفتاح السري (Secret Key)
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),                 # شكل الهيدر: Authorization: Bearer <token>
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",
    "UPDATE_LAST_LOGIN": True,
}

AUTHENTICATION_BACKENDS = (
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env("GOOGLE_CLIENT_ID")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env("GOOGLE_CLIENT_SECRET")

CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    'http://127.0.0.1:5500',
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    'http://127.0.0.1:5500',
]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # أو أي سيرفر بريد
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'shalabyziad94@gmail.com'
EMAIL_HOST_PASSWORD = 'havw dorh yzet qfxd'
DEFAULT_FROM_EMAIL = "shalabyziad94@gmail.com"

FRONTEND_URL = "http://localhost:4200"

SECURE_BROWSER_XSS_FILTER = True  # منع هجمات XSS
SECURE_CONTENT_TYPE_NOSNIFF = True  # منع التحميل غير الآمن للملفات
# SECURE_SSL_REDIRECT = True  # إجبار الموقع على HTTPS
X_FRAME_OPTIONS = "DENY"  # منع تضمين الموقع في iframes لتجنب Clickjacking


import os

# المسار الأساسي للميديا داخل المشروع
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CELERY_BROKER_URL = "redis://localhost:6379/0"  # مثال لو تستخدم Redis
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"

# maximum limits
MAX_UNPAID_ORDERS_PER_USER = 3 # أقصى عدد أوردرات غير مدفوعة لكل مستخدم
MAX_QTY_PER_ITEM = 15 # أقصى كمية لكل منتج في أي order

AVAILABLE_PAYMENT_METHODS = [
    ("COD", "Cash on Delivery"),
    ("EPAY", "E-payment"),
]

PAYMOB_PAYMENT_METHODS = [
    "mobile wallet",
    "paypal",
    "online card"
] # طرق الدفع المدعومة في Paymob

PAYMOB_SECRET_KEY = env("PAYMOB_SECRET_KEY")
PAYMOB_PUBLIC_KEY = env("PAYMOB_PUBLIC_KEY")
PAYMOB_HMAC_SECRET = env("PAYMOB_HMAC_SECRET")

# expiration settings
PAYMENT_LINK_LIFETIME_SECONDS = 600  # 10 دقيقة
SYSTEM_PAYMENT_EXPIRE_MINUTES = 15  # 15 دقيقة

ORDER_EXPIRE_MINUTES = 15  # 15 دقيقة
COOLING_PERIOD_AFTER_EXPIRY = 10 # 10 دقيقة

COD_ORDER_EXPIRE_DAYS = 3  # 3 أيام


SAMESITE = 'None'
HTTPONLY = True
SECURE = True
ACCESS_MAX_AGE = SIMPLE_JWT.get('ACCESS_TOKEN_LIFETIME')
REFRESH_MAX_AGE = SIMPLE_JWT.get('REFRESH_TOKEN_LIFETIME')
COOKIE_PATH = '/'