"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import environ

env = environ.Env()
environ.Env.read_env(env_file=BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "corsheaders",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
	'rest_framework_simplejwt',
    "django_cleanup.apps.CleanupConfig",
    'auth_app',
    "social_django",
    "product",
    "reviews",
    "cart",
    "order",
    "address",
    'django_celery_beat',
    'django_celery_results',
    "payment",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware", 
    "auth_app.authentication.CSRFMiddlewareWithJWT",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': env("DB_NAME"),
#         'USER': env("DB_USER"),
#         'PASSWORD': env("DB_PASSWORD"),
#         'HOST': env("DB_HOST"),
#         'PORT': env("DB_PORT"),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "auth_app.User" 

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "auth_app.authentication.CookieJWTAuthentication",
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10, 
}


from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12), 
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),   
    "ROTATE_REFRESH_TOKENS": True,                 
    "BLACKLIST_AFTER_ROTATION": True,             
    "ALGORITHM": "HS256",                          
    "SIGNING_KEY": SECRET_KEY,                   
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),            
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_TYPE_CLAIM": "token_type",
    "UPDATE_LAST_LOGIN": True,
}

AUTHENTICATION_BACKENDS = (
    "social_core.backends.google.GoogleOAuth2",
    "django.contrib.auth.backends.ModelBackend",
)


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = env("GOOGLE_CLIENT_ID")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = env("GOOGLE_CLIENT_SECRET")

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://angular-store.ziadshalaby95.workers.dev",
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://localhost:8000",
    "https://store.ziadshalaby00.dpdns.org",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "https://store.ziadshalaby00.dpdns.org",
]

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com" 
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
DEFAULT_FROM_EMAIL = ""

FRONTEND_URL = "http://localhost:4200"

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True 
# SECURE_SSL_REDIRECT = True  
X_FRAME_OPTIONS = "DENY"  


import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CELERY_BROKER_URL = "redis://localhost:6379/0" 
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"

# maximum limits
MAX_UNPAID_ORDERS_PER_USER = 3 
MAX_QTY_PER_ITEM = 15

AVAILABLE_PAYMENT_METHODS = [
    ("COD", "Cash on Delivery"),
    ("EPAY", "E-payment"),
]

PAYMOB_PAYMENT_METHODS = [
    "mobile wallet",
    "paypal",
    "online card"
] 

PAYMOB_SECRET_KEY = env("PAYMOB_SECRET_KEY")
PAYMOB_PUBLIC_KEY = env("PAYMOB_PUBLIC_KEY")
PAYMOB_HMAC_SECRET = env("PAYMOB_HMAC_SECRET")

# expiration settings
PAYMENT_LINK_LIFETIME_SECONDS = 600 
SYSTEM_PAYMENT_EXPIRE_MINUTES = 15 

ORDER_EXPIRE_MINUTES = 15 
COOLING_PERIOD_AFTER_EXPIRY = 10 

COD_ORDER_EXPIRE_DAYS = 3 

# Jwt Cookies
SAMESITE = 'None'
HTTPONLY = True
SECURE = True  
ACCESS_MAX_AGE = SIMPLE_JWT.get('ACCESS_TOKEN_LIFETIME')
REFRESH_MAX_AGE = SIMPLE_JWT.get('REFRESH_TOKEN_LIFETIME')
COOKIE_PATH = '/'

# CSRF
CSRF_COOKIE_NAME = "csrftoken"    
CSRF_COOKIE_SECURE = True         
CSRF_COOKIE_HTTPONLY = False      
CSRF_COOKIE_SAMESITE = "None"      
CSRF_TRUSTED_ORIGINS = [
    "https://store.ziadshalaby00.dpdns.org", 
    "https://angular-store.ziadshalaby95.workers.dev",     
]

import re

CSRF_EXEMPT_URL_PATTERNS = [
    # Payment
    re.compile(r"^/api/payment/paymob-callback/?$"),

    # Auth
    re.compile(r"^/api/auth/register/?$"),
    re.compile(r"^/api/auth/login/?$"),
    re.compile(r"^/api/auth/google-login/?$"),

    re.compile(r"^/api/auth/token/refresh/?$"),
    re.compile(r"^/api/auth/token/verify/?$"),

    re.compile(r"^/api/auth/password-reset-link/?$"),
    re.compile(r"^/api/auth/password-reset-confirm/?$"),

    re.compile(r"^/api/auth/logout/?$"),
]