# Generated by Django 5.2.6 on 2025-09-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_price_at_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid_status',
            new_name='payment_status',
        ),
    ]
