# Generated by Django 5.2.6 on 2025-09-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_shipping_address_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('unpayable', 'Unpayable'), ('expired', 'Expired')], default='unpaid', max_length=20),
        ),
    ]
