# Generated by Django 5.2.6 on 2025-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=2, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
