# Generated by Django 5.2.6 on 2025-09-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('paymob', 'Paymob Online Payment')], default='paymob', max_length=20),
        ),
    ]
