# Generated by Django 5.2.6 on 2025-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('mobile wallet', 'Mobile wallet'), ('paypal', 'Paypal'), ('online card', 'Online card')], default='cod', max_length=20),
        ),
    ]
