# Generated by Django 5.2.6 on 2025-09-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('mobile wallet', 'Mobile wallet'), ('paypal', 'Paypal'), ('online card', 'Online card')], max_length=20),
        ),
    ]
