# Generated by Django 5.2.6 on 2025-09-13 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_remove_order_shipping_address_orderaddress'),
        ('product', '0005_remove_product_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='p_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='p_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='p_name',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
