# Generated by Django 5.2.6 on 2025-09-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_orderitem_p_description_orderitem_p_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('expired', 'Expired')], default='unpaid', max_length=20),
        ),
    ]
